// generated by go generate; DO NOT EDIT

package main

import "html/template"

var (
	indexTmpl          = template.Must(template.New("").Funcs(fns).Parse(baseTemplate + navTemplate + indexTemplate))
	loginTmpl          = template.Must(template.New("").Funcs(fns).Parse(baseTemplate + loginTemplate))
	safeTmpl           = template.Must(template.New("").Funcs(fns).Parse(baseTemplate + navTemplate + safeTemplate))
	tagApprovalTmpl    = template.Must(template.New("").Funcs(fns).Parse(baseTemplate + navTemplate + tag_approvalTemplate))
	tagHistoryDiffTmpl = template.Must(template.New("").Funcs(fns).Parse(baseTemplate + navTemplate + tag_history_diffTemplate))
	tagHistoryTmpl     = template.Must(template.New("").Funcs(fns).Parse(baseTemplate + navTemplate + tag_historyTemplate))
	tagsDiffTmpl       = template.Must(template.New("").Funcs(fns).Parse(baseTemplate + navTemplate + tags_diffTemplate))
	userFindTmpl       = template.Must(template.New("").Funcs(fns).Parse(baseTemplate + navTemplate + user_findTemplate))
)

const (
	baseTemplate = `
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Kanri - {{block "title" .}}{{end}}</title>
	<script type='text/javascript'>
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', '{{.Common.AnalyticsID}}']);
		_gaq.push(['_trackPageview']);
		(function() {
		  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	</script>
	<meta name="description" content="{{.Common.Description}}">
	<meta name="keywords" content="{{.Common.Keywords}}">
	<style>
		body {
			font-size: 16px;
			line-height: 1.2;
			font-family: Verdana, Geneva, sans-serif;
		}
		a:link {
			color:#006FFA;
			text-decoration:none;
		}
		a:visited {
			color:#006FFA;
			text-decoration:none;
		}
		a:hover {
			color:#33CFFF;
			text-decoration:none;
		}
		a:active {
			color:#006FFA;
			text-decoration:none;
		}

		p, a, span {font-size: 120%;}

		body {
			list-style-type: none;
			padding-top: 0;
			margin-top: 0;
		}

		#site-title {
			font-size: 133%;
			padding: 0.5em;
			margin: 0;
		}

		#subnav {
		    background: #f6f6f6;
			padding-top: 1em;
			padding-bottom: 1em;
			border-top: 1px #ebebeb solid;
			border-bottom: 1px #ebebeb solid;
		}

		#subnav a {
		    padding: 0.5em;
		}

		#subnav subnav-button-link {
		    padding: 0.5em;
		}

		.subnav-button-form {
			display: inline;
		}

		.subnav-button-link {
			background: none!important;
			border: none;
			padding: 0!important;
			font: inherit;
			font-size: 120%;
			cursor: pointer;
			color: #006FFA;
			display: inline;
		}

		.subnav-button-link:visited {
			color:#006FFA;
			text-decoration:none;
		}
		.subnav-button-link:hover {
			color:#33CFFF;
			text-decoration:none;
		}
		.subnav-button-link:active {
			color:#006FFA;
			text-decoration:none;
		}

		#login-form label, #login-form input, #login-form button, #login-form em {
			padding: 0.5em;
			display: block;
			font-size: 120%;
			line-height:1.2;
		}

		#login-form button {
			margin-top: 0.5em;
		}

		#login-form h1 {
			padding: 0.5em;
			font-size: 120%;
		}

		.toolbar {
			padding: 0.5em;
		}
		.toolbar input, .toolbar button {
			font-size: 120%;
		}

		.suggestion {
			padding: 0.5em;
			border-top: 1px #ebebeb solid;
			border-bottom: 1px #ebebeb solid;
			border-left: 0.3em #006FFA solid;
			border-top-left-radius: 0.3em;
			border-bottom-left-radius: 0.3em;
			line-height: 200%;
		}

		.suggestion form {
			display: inline;
		}

		.suggestion textarea {
			display: block;
			font-size: 120%;
			line-height:1.2;
		}
		.suggestion:nth-of-type(even) {
		    background: #f6f6f6;
		}

		.suggestion-form {
			padding: 0.5em;
			line-height: 200%;
		}

		textarea {
			width: 70%;
		}
		@media (max-width: 768px) {
			textarea {
				width: 100%;
			}
		}

		.suggestion-form input[type=submit] {
			padding: 0.5em;
			margin-top: 0.5em;
			display: block;
		}

		.alert {
			border-radius: 4px;
			padding: 1em;
			margin-top: 0.5em;
			margin-bottom: 0.5em;
			font-size: 120%;
			width: 70%;
		}
		.alert strong {
			font-size: inherit;
		}
		@media (max-width: 768px) {
			.alert{
				width: 90%;
				padding-left:5%;
				padding-right:5%;
			}
		}

		.alert-success {
			color: #3c763d;
			background-color: #dff0d8;
			border-color: #d6e9c6;
		}

		.alert-error {
			color: #a94442;
			background-color: #f2dede;
			border-color: #ebccd1;
		}

		.alert-info {
			color: #31708f;
			background-color: #d9edf7;
			border-color: #bce8f1;
		}

		footer {
			color: #ccc;
			font-size: 0.9em;
			padding-left: 0.5em;
			padding-top: 1em;
		}

		footer a {
			font-size: 0.9em;
		}



	</style>
	{{block "css" .}}{{end}}
</head>
<body>
	<h1 id="site-title"><a href="/post/list">{{.Common.SiteTitle}}</a></h1>
	{{block "subnav" .}}{{end}}
	{{block "content" .}}{{end}}
	<footer>
		{{block "footer" .}}{{end}}
		<em>Served by <a href="https://github.com/kusubooru/kanri">kanri</a> {{printv .Version}}</em>
	</footer>
</body>
</html>
`
	indexTemplate = `
{{define "title"}}Home{{end}}
{{define "content"}}
<h1>Management tools for shimmie</h1>
{{end}}
`
	loginTemplate = `
{{define "content"}}
<form id="login-form" method="post" action="/kanri/login/submit">
<h1>Login</h1>
    <label for="username">User name</label>
    <input type="text" id="username" name="username">
    <label for="password">Password</label>
    <input type="password" id="password" name="password">
    <button type="submit">Login</button>
	{{if .Data}}
	<em>{{.Data}}</em>
	{{end}}
</form>
{{end}}
`
	navTemplate = `
{{define "subnav"}}
<div id="subnav">
	<a href="/kanri">Index</a>
	<a href="/kanri/safe">Safe Approval</a>
	<a href="/kanri/tags/approval">Tag Approval</a>
	<a href="/kanri/tags/history">Tag History</a>
	<a href="/kanri/tags/diff">Tags Diff</a>
	<a href="/kanri/user/find">User Find</a>
	<form class="subnav-button-form" method="post" action="/kanri/logout">
	     <input class="subnav-button-link" type="submit" value="Logout">
	</form>
</div>
{{end}}
`
	safeTemplate = `
{{define "title"}}Safe Approval{{end}}
{{define "css"}}
<style>
	.safe {
		margin: 0.5em;
		display: block;
		overflow: auto;
	}
	.safe-body form  {
		font-size: 120%;
		line-height: 1.2;
	}
	.safe-body span  {
		font-size: 120%;
		line-height: 1.2;
	}
	.safe-thumb {
		float: left;
		min-width: 192px;
		min-height: 192px;
	}
	.safe-body {
		padding: 0.5em;
		overflow: auto;
		display: block;
		line-height: 1.2;
	}
	.safe-body input[type="submit"] {
		padding: 0.5em;
		margin: 0.5em;
	}
</style>
{{end}}
{{define "content"}}
{{range .Data}}
<div class="safe">
	<div class="safe-thumb">
		<a href="/kanri/_image/{{.Hash}}"><img src="/kanri/_thumb/{{.Hash}}"></a>
	</div>
	<div class="safe-body">
		<span><a href="/post/view/{{.ID}}">#{{.ID}}</a> Rated by: {{.Rater}} ({{.RaterIP}}) on {{.RateDateFormat}}</span>
		<form method="POST" action="/kanri/safe/rate">
			<input type="hidden" name="id" value="{{.ID}}">
			<input id="sInput{{.ID}}" type="radio" name="rating" value="s" {{if eq .Rating "s"}}checked{{end}}>
			<label for="sInput{{.ID}}">Safe</label>
			<input id="qInput{{.ID}}" type="radio" name="rating" value="q" {{if eq .Rating "q"}}checked{{end}}>
			<label for="qInput{{.ID}}">Questionable</label>
			<input id="eInput{{.ID}}" type="radio" name="rating" value="e" {{if eq .Rating "e"}}checked{{end}}>
			<label for="eInput{{.ID}}">Explicit</label>
			<input type="submit" value="Rate">
		</form>
	</div>
</div>
{{else}}

<div class="alert alert-success">
	<strong>Woot:</strong> Every image rating is approved!
</div>
{{end}}
{{end}}
`
	tag_approvalTemplate = `
{{define "title"}}Tag History{{end}}
{{define "css"}}
<style>
	.tag-approval-form {
		margin: 0.5em;
	}
	.tag-approval-form input {
		font-size: 120%;
		padding: 0.5em;
	}
	.tag-approval {
		padding: 0.5em;
	}
</style>
{{end}}
{{define "content"}}
<div class="tag-approval-form">
	<form>
		<input type="text" name="ownerUsername" placeholder="Enter owner username">
		<input type="submit" value="Get contributed tag history">
	</form>
</div>
{{if .Data}}
{{range $i, $e := .Data}}
<div class="tag-approval">
	<span><a href="/kanri/tags/history?imageID={{.ImageID}}">#{{.ImageID}}</a> Set by: {{.TaggerName}} ({{.TaggerIP}}) on {{.DateSet}}</span>
	<div>{{.Tags}}</div>
</div>
{{end}}

{{else}}
<div class="alert alert-info">
	<strong>Info:</strong> No contributed tag history found for this user.
</div>

{{end}}
{{end}}
`
	tag_historyTemplate = `
{{define "title"}}Tag History{{end}}
{{define "css"}}
<style>
	.tag-history-form {
		margin: 0.5em;
	}
	.tag-history-form input {
		font-size: 120%;
		padding: 0.5em;
	}
	.compare-form input {
		font-size: 120%;
		padding: 0.5em;
	}
	.compare-form input[type="submit"] {
		font-size: 120%;
		padding: 0.5em;
		margin: 0.5em;
	}
	.tag-history {
		padding: 0.5em;
	}
</style>
{{end}}
{{define "content"}}
<div class="tag-history-form">
	<form>
		<input type="text" name="imageID" placeholder="Enter image ID">
		<input type="submit" value="Get tag history">
	</form>
</div>
{{if .Data}}
<form action="/kanri/tags/history/diff" class="compare-form">
	<input type="submit" value="Compare">
	{{range $i, $e := .Data}}
	<div class="tag-history">
		<input type="radio" name="new" {{if eq $i 0 }}checked{{end}} value="{{.ID}}">
		<input type="radio" name="old" {{if eq $i 1 }}checked{{end}} value="{{.ID}}">
		<span><a href="/post/view/{{.ImageID}}">#{{.ImageID}}</a> Set by: {{.Name}} ({{.UserIP}}) on {{.DateSet}}</span>
		<div>{{.Tags}}</div>
	</div>
	{{end}}
	<input type="hidden" value="{{(index .Data 0).ImageID}}" name="imageID">
	<input type="submit" value="Compare">
</form>

{{else}}
<div class="alert alert-info">
	<strong>Info:</strong> No tag history for this image.
</div>

{{end}}
{{end}}
`
	tag_history_diffTemplate = `
{{define "title"}}Tags Diff{{end}}
{{define "css"}}
<style>
	.tag-history {
		margin: 0.5em;
		display: block;
		overflow: auto;
		line-height: 1.2;
	}
	.diff {
		margin: 0.5em;
		font-family: monospace;
	}
	.removed {
		color: darkred;
	}
	.added {
		color: darkgreen;
	}
</style>
{{end}}
{{define "content"}}
{{if .Data}}
	{{with .Data}}
	<div class="tag-history">
		{{with .New}}
		<span><a href="/post/view/{{.ImageID}}">#{{.ImageID}}</a>  ({{.UserIP}}) on {{.DateSet}}</span>
		<div>{{.Tags}}</div>
		{{end}}
	</div>
	<div class="tag-history">
		{{with .Old}}
		<span><a href="/post/view/{{.ImageID}}">#{{.ImageID}}</a>  ({{.UserIP}}) on {{.DateSet}}</span>
		<div>{{.Tags}}</div>
		{{end}}
	</div>
	<div id="diff" class="diff">
		{{ range $r := .Removed }}
			<li><strong class="removed">---</strong> {{ $r }}</li>
		{{ end }}
		{{ range $a := .Added }}
			<li><strong class="added">+++</strong> {{ $a }}</li>
		{{ end }}
	</div>
	{{end}}

{{else}}
<div class="alert alert-info">
	<strong>Info:</strong> Compare what?
</div>
{{end}}
{{end}}
`
	tags_diffTemplate = `
{{define "title"}}Tags Diff{{end}}
{{define "css"}}
<style>
	.diff-form {
		margin: 0.5em;
	}
	.diff-form textarea {
		font-size: 120%;
		display: block;
		margin: 0.5em;
	}
	.diff-form label {
		font-size: 120%;
		padding: 0.5em;
	}
	.diff-form input[type="submit"] {
		font-size: 120%;
		padding: 0.5em;
		margin: 0.5em;
	}
	.diff {
		margin: 0.5em;
		font-family: monospace;
	}
	.removed {
		color: darkred;
	}
	.added {
		color: darkgreen;
	}
</style>
{{end}}
{{define "content"}}
	{{with .Data}}
	<form method="post" class="diff-form">
		<label for="old"><strong>Old Tags</strong></label>
		<textarea id="old" name="old" cols="60" rows="7">{{ .Old }}</textarea>
		<label for="new"><strong>New Tags</strong></label>
		<textarea id="new" name="new" cols="60" rows="7">{{ .New }}</textarea>
		<input type="submit" value="Compare">
	</form>
	<div id="diff" class="diff">
		{{ range $r := .Removed }}
			<li><strong class="removed">---</strong> {{ $r }}</li>
		{{ end }}
		{{ range $a := .Added }}
			<li><strong class="added">+++</strong> {{ $a }}</li>
		{{ end }}
	</div>
	{{end}}
{{end}}
`
	user_findTemplate = `
{{define "title"}}Find User{{end}}
{{define "css"}}
  <style>
    .user-find-form {
      margin: 0.5em;
    }
    .user-find-form input {
      font-size: 120%;
      padding: 0.5em;
    }
    .user-find{
      font-size: 120%;
      margin: 0.5em;
    }
    .user-find input {
      padding: 0.5em;
    }
    .user-find label {
      padding: 0.5em;
    }
    .user-stat {
      display: block;
    }
  </style>
{{end}}

{{define "content"}}
  <div class="user-find-form">
    <form method="POST" action="/kanri/user/find">
      <input type="text" name="userID" placeholder="Enter user ID">
      <input type="submit" value="Find user">
    </form>
  </div>

  {{if .Data}}
    {{with .Data}}
    <div class="user-find">
      <span class="user-stat" id="userIDField"><label for="userIDField">ID:</label> <a href="/user/{{.Name}}">#{{.ID}}</a></span>
      <span class="user-stat" id="userNameField"><label for="userNameField">Name:</label> {{.Name}}</span>
      <span class="user-stat" id="userClassField"><label for="userClassField">Class:</label> {{.Class}}</span>
      <span class="user-stat" id="userJoinedField"><label for="userJoinedField">Joined:</label> {{formatTime .JoinDate}}</span>
      <span class="user-stat" id="userEmailField"><label for="userEmailField">Email:</label> {{filterEmpty .Email "-"}}</span>
    </div>
    {{end}}

  {{else}}
    <div class="alert alert-info">
      <strong>Info:</strong> No user with that ID found.
    </div>
  {{end}}
{{end}}
`
)
